site_name: KG.NEwTechEnergy
copyright: Copyright &copy; 2016 - 2024 KGNeTE
dev_addr: 0.0.0.0:8000

theme:
  name: material
  logo:  /img/logo.png
  favicon: /img/logo.png

  palette:
    primary: white
    accent: orange

  # palette:
  #   - scheme: slate
  #     primary: blue grey
  #     accent: orange

  features:
    - navigation.tabs
    - toc.integrate 
  language: es

plugins:
  - blog:
      post_excerpt_separator: pagina_1.png
      # # categories_toc: true
      # blog_toc: true
      # # blog_dir: bbb


  # - privacy
  - search
  
extra_javascript:
  - js/pdfjs/pdf.mjs
  
extra:
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXX
  consent:
    title:  Consentimiento de Cookies
    description: >- 
      Utilizo cookies para reconocer sus visitas y para medir la eficacia de mi documentación.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
    actions:
      - accept
      - reject  
  alternate:
    - name: English 
      link: /
      lang: en
    - name: Español
      link: /
      lang: es
    - name: Italiano
      link: /
      lang: it


  social:
    - icon: fontawesome/brands/whatsapp 
      link: https://api.whatsapp.com/send?phone=34600366211
    - icon: fontawesome/solid/phone
      link: tel:+34 600366211
    - icon: material/email
      link: mailto:kgnete@gmail.com
    # - icon: fontawesome/brands/github
    #   link: https://github.com/kgnete
    # - icon: fontawesome/brands/stack-overflow
    #   link: https://stackoverflow.com/users/3788513/kgnete
    # - icon: fontawesome/brands/kaggle
    #   link: https://www.kaggle.com/kgnete
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/u/kgnete
    # - icon: fontawesome/brands/x-twitter 
    #   link: https://twitter.com/kgnete
    # - icon: fontawesome/brands/facebook 
    #   link: https://www.facebook.com/kgnete
    # - icon: fontawesome/brands/linkedin 
    #   link: https://www.linkedin.com/in/k-gnete-590154165/
    # - icon: fontawesome/brands/instagram 
    #   link: https://www.instagram.com/kgnete/

markdown_extensions:
  - meta
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
