authors:
  KGNeTE:
    name: KGNeTE
    description: Efficiency & Renewable Energy Technologies
    avatar: /img/logo.png
  Aislada:
    name: Aislada
    description: Fotovoltaica
    avatar: /img/logo.png
